<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.example.demo.architecture.commons.exception.GlobalExceptionHandlerTest" tests="4" skipped="0" failures="0" errors="0" timestamp="2024-08-26T04:33:23" hostname="CL-IT01235" time="0.024">
  <properties/>
  <testcase name="testHandleGenericException()" classname="com.example.demo.architecture.commons.exception.GlobalExceptionHandlerTest" time="0.013"/>
  <testcase name="testHandleDuplicateUserException()" classname="com.example.demo.architecture.commons.exception.GlobalExceptionHandlerTest" time="0.0"/>
  <testcase name="testHandleValidationErrors()" classname="com.example.demo.architecture.commons.exception.GlobalExceptionHandlerTest" time="0.007"/>
  <testcase name="testHandleRuntimeException()" classname="com.example.demo.architecture.commons.exception.GlobalExceptionHandlerTest" time="0.001"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
