<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="es"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>GlobalExceptionHandler.java</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">demo</a> &gt; <a href="index.source.html" class="el_package">com.example.demo.architecture.commons.exception</a> &gt; <span class="el_source">GlobalExceptionHandler.java</span></div><h1>GlobalExceptionHandler.java</h1><pre class="source lang-java linenums">package com.example.demo.architecture.commons.exception;

import org.apache.coyote.BadRequestException;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.FieldError;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;

@ControllerAdvice
<span class="fc" id="L12">public class GlobalExceptionHandler {</span>

    @ExceptionHandler(DuplicateUserException.class)
    public ResponseEntity&lt;ErrorResponse&gt; handleDuplicateUserException(DuplicateUserException ex) {
<span class="fc" id="L16">        ErrorResponse errorResponse = new ErrorResponse(</span>
                &quot;El correo ya está registrado&quot;,
<span class="fc" id="L18">                ex.getMessage(),</span>
                HttpStatus.BAD_REQUEST,
<span class="fc" id="L20">                HttpStatus.BAD_REQUEST.value()</span>
        );
<span class="fc" id="L22">        return new ResponseEntity&lt;&gt;(errorResponse, HttpStatus.BAD_REQUEST);</span>
    }
    @ExceptionHandler(BadRequestException.class)
    public ResponseEntity&lt;ErrorResponse&gt; handleBadRequestrException(BadRequestException ex) {
<span class="nc" id="L26">        ErrorResponse errorResponse = new ErrorResponse(</span>
                &quot;Error en la petición&quot;,
<span class="nc" id="L28">                ex.getMessage(),</span>
                HttpStatus.BAD_REQUEST,
<span class="nc" id="L30">                HttpStatus.BAD_REQUEST.value()</span>
        );
<span class="nc" id="L32">        return new ResponseEntity&lt;&gt;(errorResponse, HttpStatus.BAD_REQUEST);</span>
    }


    @ExceptionHandler(RuntimeException.class)
    public ResponseEntity&lt;ErrorResponse&gt; handleRuntimeException(RuntimeException ex) {
<span class="fc" id="L38">        ErrorResponse errorResponse = new ErrorResponse(</span>
                &quot;Error en tiempo de ejecución&quot;,
<span class="fc" id="L40">                ex.getLocalizedMessage(),</span>
                HttpStatus.INTERNAL_SERVER_ERROR,
<span class="fc" id="L42">                HttpStatus.INTERNAL_SERVER_ERROR.value()</span>
        );
<span class="fc" id="L44">        return new ResponseEntity&lt;&gt;(errorResponse, HttpStatus.INTERNAL_SERVER_ERROR);</span>
    }

    @ExceptionHandler(Exception.class)
    public ResponseEntity&lt;ErrorResponse&gt; handleGenericException(Exception ex) {
<span class="fc" id="L49">        ErrorResponse errorResponse = new ErrorResponse(</span>
                &quot;Error interno del servidor&quot;,
<span class="fc" id="L51">                ex.getLocalizedMessage(),</span>
                HttpStatus.INTERNAL_SERVER_ERROR,
<span class="fc" id="L53">                HttpStatus.INTERNAL_SERVER_ERROR.value()</span>
        );
<span class="fc" id="L55">        return new ResponseEntity&lt;&gt;(errorResponse, HttpStatus.INTERNAL_SERVER_ERROR);</span>
    }

    @ExceptionHandler(MethodArgumentNotValidException.class)
    public ResponseEntity&lt;ErrorResponse&gt; handleValidationErrors(MethodArgumentNotValidException ex) {
<span class="fc" id="L60">        ErrorResponse errorResponse = new ErrorResponse(</span>
                &quot;Error con los parámetros ingresados&quot;,
                &quot;Validación fallida para uno o más campos.&quot;,
                HttpStatus.BAD_REQUEST,
<span class="fc" id="L64">                HttpStatus.BAD_REQUEST.value()</span>
        );
<span class="fc bfc" id="L66" title="All 2 branches covered.">        for (FieldError error : ex.getBindingResult().getFieldErrors()) {</span>
<span class="fc" id="L67">            errorResponse.addValidationError(error.getField(), error.getDefaultMessage());</span>
<span class="fc" id="L68">        }</span>
<span class="fc" id="L69">        return new ResponseEntity&lt;&gt;(errorResponse, HttpStatus.BAD_REQUEST);</span>
    }
}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.12.202403310830</span></div></body></html>